@echo off
rem ----- Auto-generated by make.sh and Linux make system do not modify

rem ----- shut up DOS4G/W
set DOS4G=quiet

if "%1" == "clean" call clean.bat
if "%1" == "clean" goto end

mkdir dos86c
wmake -f ..\..\mak\dos86c.mak HPS=\ all REL=..\.. 

mkdir dos86l
wmake -f ..\..\mak\dos86l.mak HPS=\ all REL=..\.. 

mkdir dos86m
wmake -f ..\..\mak\dos86m.mak HPS=\ all REL=..\.. 

mkdir dos86s
wmake -f ..\..\mak\dos86s.mak HPS=\ all REL=..\.. 

mkdir dos386f
wmake -f ..\..\mak\dos386f.mak HPS=\ all REL=..\.. 


:end
