#!/bin/bash
# sort of like svn-update-all
./cleantree 2>/dev/null
./cleanup.sh 2>/dev/null
for i in \* \*/\* \*/\*/\*; do git add $i 2>/dev/null; done
git commit -a
./cleantree 2>/dev/null
git push
git pull

