@echo off
rem ----- Auto-generated by make.sh and Linux make system do not modify

rem ----- shut up DOS4G/W
set DOS4G=quiet

if "%1" == "clean" call clean.bat
if "%1" == "clean" goto end

mkdir win313l
wmake -f ..\..\mak\win313l.mak HPS=\ all REL=..\.. 


:end
