[autoexec]
mount c: .
c:

tool\tasm /la test1.asm,dos86t\test1.obj
tool\tlink /Tdc dos86t\test1.obj,dos86t\test1.com

tool\tasm /la test2.asm,dos86t\test2.obj
tool\tlink /Tdc dos86t\test2.obj,dos86t\test2.com

tool\tasm /la test3.asm,dos86t\test3.obj
tool\tlink /Tdc dos86t\test3.obj,dos86t\test3.com

tool\tasm /la test4.asm,dos86t\test4.obj
tool\tlink /Tdc dos86t\test4.obj,dos86t\test4.com

exit

