@echo off
rem ----- Auto-generated by make.sh and Linux make system do not modify

rem ----- shut up DOS4G/W
set DOS4G=quiet

if "%1" == "clean" call clean.bat
if "%1" == "clean" goto end

mkdir winnt
wmake -f ..\..\mak\winnt.mak HPS=\ all REL=..\.. 

mkdir win32
wmake -f ..\..\mak\win32.mak HPS=\ all REL=..\.. 


:end
