@echo off
rem ----- Auto-generated by make.sh and Linux make system do not modify

rem ----- shut up DOS4G/W
set DOS4G=quiet

if "%1" == "clean" call clean.bat
if "%1" == "clean" goto end

mkdir os2w2l
wmake -f ..\..\mak\os2w2l.mak HPS=\ all REL=..\.. 

mkdir os2d3f
wmake -f ..\..\mak\os2d3f.mak HPS=\ all REL=..\.. 


:end
